### PR TITLE
Connect network and client

### PR DESCRIPTION
**Pull request by Anastasia-Tre**

### CODE REVIEW

**Comment by VsIG-official** [comment]
Can You see Players and\or food in game view?

**Comment by Anastasia-Tre** [comment]
I can see them only in scene, and I don't know how to fix it

**Comment by VsIG-official** [comment]
Ok, We can merge it now and I'll try to fix it

**Review by VsIG-official — APPROVED** [review]

**Comment by VsIG-official** [comment]
> I can see them only in scene, and I don't know how to fix it

Fixed in #22

**Pull request merged**
